### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cbartlett** [dtao/nearest-color#13]
Hello, I am interesting in using this library but I could not find a license for it.

Any chance you could license this as MIT? Github makes it easy to add a license: https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

Or if you concur, I could add the license and PR it.

**Comment by cbartlett** [comment]
PS: I probably should have lead with THANK YOU for writing this, it's exactly what I need. 😬

**Comment by dtao** [comment]
Hi @cbartlett! Yes, I normally go with the MIT license. If you create a PR to add that I'll merge it :)
