### ISSUE TITLE
Cannot read property 'r' of null - React ES6 Project

### ISSUE THREAD

**Issue by tmhn** [dtao/nearest-color#2]
I currently have a JSON object that holds a number of color names and hex codes within my React project and am wanting to use `nearest-color` to show a user the nearest color to one they have entered in a HTML input field.

```javascript

handleSearch(e) {
    let color = `#${e.target.value.replace("#", "")}`;

    if (color.length == 7) {

        let tempColors = this.state.colors;
        let colorsObj = {};

        // Iterates over state and creates a JSON Object with {color-name(key): color-hex(value)}
        for (let i = 0; i < tempColors.length; i++) {
            colorsObj[tempColors[i]] = Base[tempColors[i]]
        }

        var nearestColor = require('nearest-color').from(colorsObj);
        var newColor = nearestColor(color)
        console.log(newColor)
    }
}
```

My code compiles, however I receive this problem in Chrome when I enter a hex code such as `#ffffff`: 

![screen shot 2016-12-20 at 17 32 58](https://cloud.githubusercontent.com/assets/6421923/21361103/76eaffba-c6da-11e6-9caa-b73562312071.png)

I've followed the README.md, so I'm not entirely sure where my code is falling over sadly.

**Comment by dtao** [comment]
Hmm, I'll need to look into this. Since you've included a code snippet with some missing data, though, it's hard to guess at what could be wrong. Do you still have access to the code? Could you share with me what `colorsObj` is at the point where you're using it? (You could add `console.dir(colorsObj)` right above the line starting with `var nearestColor` and just let me know what you see.)

**Comment by Zequez** [comment]
Might be the fact that if you don't name your colors it doesn't return an object with the `{rgb}` key, and then you're trying to read `{rgb: { r }}`? That happened to me :P

**Comment by hesamd** [comment]
I had the same issue. I resolved it by adding `#` to my hex color codes.

**Comment by yastrebovb** [comment]
> Might be the fact that if you don't name your colors it doesn't return an object with the `{rgb}` key, and then you're trying to read `{rgb: { r }}`? That happened to me :P

Thanks!
