### ISSUE TITLE
Feature request: exclude colors

### ISSUE THREAD

**Issue by meodai** [dtao/nearest-color#3]
I am using the function to generate color names for generated color palettes.  I want to make sure that every name is only used once per palette. For that it would be super nice if you could provide a list of colors to exclude.

Something like:
```
nearestColor('#800', ['#801', '#802', '#f02']);
```

My first thought was to exclude the matches from the list by calling splice() on my names array, but  counts around 4500 color names.

(this is the list I am using: https://github.com/meodai/color-names)

**Comment by dtao** [comment]
I'm not sure I understand the request. You want to specify a list of colors that should be excluded from the set of possible matches? Why not just exclude those colors from the set of possible matches to begin with?

**Comment by meodai** [comment]
because  I want every color name to be used only once per palette: http://s.codepen.io/meodai/debug/60a1e733a66f4ec4718254e91cd8e4c4 (sometimes when colors are close-by in the RGB space the get the same name) Manipulating the the array with nearly 5000 entries would be killing the performance.

So what you are suggesting is removing the used color form the array:
let color and creating a new instance of nearest color every time?
```
let nc = require('nearest-color');
let massiveColorArray = [...];
let massiveColorArrayMinuesTheAlreadyUsedOnes = massiveColorArray.slice();
let lotsOfColorsIneedUniqueNamesFor = [...];

let namesForMyPalette = lotsOfColorsIneedUniqueNamesFor.map(color => {
   const nearestColor = nc.from(massiveColorArrayMinuesTheAlreadyUsedOnes);
  massiveColorArrayMinuesTheAlreadyUsedOnes =  massiveColorArrayMinuesTheAlreadyUsedOnes.splice(indexThatIGotSomehow, indexThatIGotSomehow + 1);
   return nearestColor(color);
});

```

**Comment by meodai** [comment]
PS: its crazy fast by the way even with 8000 entries: https://codepen.io/meodai/full/bWOBja/

**Comment by meodai** [comment]
ping?

**Comment by dtao** [comment]
Having read through both your comments and the source (!) again, I think I better understand what you're asking.

My feeling is that the interface for this library hides too much. It should be possible to call `nearestColor` and pass a list of color candidates. This would allow you on the calling side to remove candidates one by one with each call (rather than *adding* to a list of colors to exclude).

Does that sound reasonable to you? If so that shouldn't be hard to do.

**Comment by meodai** [comment]
@dtao Sounds veery reasonable. I am relaying so much on this library lately. Thanks again!
